{% set name = "lazy_table" %}
{% set version = "0.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lazy-table-{{ version }}.tar.gz
  sha256: cc724a895ad55f3b65129a95f4bab58b5787a03d282470c4ddb02ff33386d433

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - tabulate
    - tqdm

test:
  imports:
    - lazy_table
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/parsiad/lazy-table
  summary: A python-tabulate wrapper for producing tables from generators
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
